apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    acornsoft.io/workload-group-no: "5"
  generation: 4
  labels:
    app: commerce-hj-product
  name: commerce-hj-product
  namespace: commerce-hj
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: commerce-hj-product
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: commerce-hj-product
        version: v1
    spec:
      containers:
      - image: 192.168.100.12/commerce-hj/commerce-hj-product:latest
        imagePullPolicy: Always
        name: commerce-hj-product
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: commerce-cocktail-t8ceb0dry5v7
